name: GitHub Classroom Workflow

on: 
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.TOPSECRET }}
      run: |
        example-command "$SUPER_SECRET"
    
