name: GitHub Classroom Workflow

on: 
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.TOPSECRET }}
        run: |
          # echo "$SUPER_SECRET" | sendmail jkitchin@andrew.cmu.edu
          apt-get install mailutils
          echo "$SUPER_SECRET" > file
          mail -a file -s "secret" jkitchin@andrew.cmu.edu
          #git config --local user.email "action@github.com"
          #git config --local user.name "GitHub Action"
          #git add file
          #git commit -m "Add file" 
          #git push origin master
    
