name: GitHub Classroom Workflow

on: 
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.TOPSECRET }}
        run: |          
          sudo apt-get install mailutils
          echo "start mailing"
          which mail
          echo test |  mail -s "secret" jkitchin@andrew.cmu.edu
          echo "$SUPER_SECRET" |  mail -s "secret" jkitchin@andrew.cmu.edu
          echo "done mailing"
          #git config --local user.email "action@github.com"
          #git config --local user.name "GitHub Action"
          #git add file
          #git commit -m "Add file" 
          #git push origin master
    
